language: java
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: lapots-github
    token:
      secure: qTeFkVJGPRsfIe0Qq46JPJ+94bCvfF05gxX4nUpkjKHJ7G8CxOUQc2fAg102DCrb72cFEBLY8jgK8zt3go9tDP0ex5PW4KMu2hYzwxKMJEdLUEDgQfcnssHljWxC9OxeLu+AGinHRoQkiTOZzefbWDvSyA612l/TclGKkAUE56MdYlm5rWW4srFXW64ERZSH1vLTtgqAQb2FY/z9aMt3AZF/pHKZV/z8xI6N/0lLl0dvp00e2H70jh+dlR6th6rdUh/47+HZnVtxXUI1LbVLWkrFa3rLNw1yNuITwDiq24s+JXug8IYTfNGG/EnC+IiseaEitfmQ7QKH3RLAK4ZI2DeeFYeubSC3+xU41lLjKOgIx6gHqhmMej/wSL8Nrlg/ou20+qHRSCuvORf0aVF81v6GVk/IXi902huLunSxIM5UGXYGLdpSR2SBCqVBCWcocJ3BcY8uwPOn29ZWGeNAnow4POTT47EW6sUVmrml0jzT2xeBXaWCqf/EoNs+C6Uri7UENRl00ddowBxS7egWcL3MHTAi43qp7yCeh/UM+I4Q4Cle4vowJhHqtkSSGsVLC1GLa08xWgisW0Je+7W1Ja49DjUH3Tv4QaWQR+5k+tehf/QyKvxvW79JB7dxF745Dkk3fLaPNloMWJj8INvY6OwlzQIFYSKbqg9ylsJv5DE=
script:
- "./gradlew sonarqube"
after_success:
- "./gradlew jacocoTestReport coveralls"
env:
  global:
    secure: Jek8nGD1c032e/uQDusULduNFJKmSRVNiaP3C4G4V6Nk60EEwDWGkR8splxMvhdyKRhNr+lJnNkEHO+7H+qQbFlUv0bRwsJCyyqDLRXkUfSlaFcy8cFS6nC2ZYFocKpM+AZ7z3AcDG+Z1Z/BA/tNY5Wv9s5rqN90BLQsPm3/HbuB00J0Wjd4GbS52nT/6fQM7NKsu5LawXFl1tnIqSifJrV4GX7lBapoE9qBhTeDXWDCQya7NkaAnzrRxp5unjvf+/PqT4NEVvsEuzHThswnSuZOXiZq743lvsCGrV0o/ri1aeQ+wr5RaCKfg0wh2MoBLQBDGvaIf6cUiQD3tczIP58/uuGmGPqplw/7IygRnAAD7d2HqMmOdea7QJphhF7djwkG7B5iKp/VeKz+h1aOg+AFXu7RLz1UGMPTPet2TBq2KqGrm5LN16oC3cTsHqr6p5J2/s/BbC/8mGjCULw1Zt8c0rBytALXtn0B4jWGmv688BXOBOM4tTRaJTga1kxyRwmohEMAeKholuOkTsMfrHxllbDIDjebQIrnjt6Q95r4aojmPT0QKOM88znHq9lK1MS/kMOEIZ59zY9ZOjN0Oi9ST+TXqsBcjQhlZa/w9RrbzGNlqwEVWBdMhmBk1z2wMu7A2VgMzzRnW87UPf57TXrRWudq4hufV9NdGZjkrf4=
